/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bindListener.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e8dfc4df9cc6fdc0a7da7522741b970e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dsmx/bindListener.h>
// pydoc.h is automatically generated in the build directory
#include <bindListener_pydoc.h>

void bind_bindListener(py::module& m)
{

    using bindListener    = ::gr::dsmx::bindListener;


    py::class_<bindListener, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<bindListener>>(m, "bindListener", D(bindListener))

        .def(py::init(&bindListener::make),
           D(bindListener,make)
        )
        



        ;




}








