/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Despreader.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f89d39b69436509036fed9551939428f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dsmx/Despreader.h>
// pydoc.h is automatically generated in the build directory
#include <Despreader_pydoc.h>

void bind_Despreader(py::module& m)
{

    using Despreader    = ::gr::dsmx::Despreader;


    py::class_<Despreader, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<Despreader>>(m, "Despreader", D(Despreader))

        .def(py::init(&Despreader::make),
           D(Despreader,make)
        )
        



        ;




}








